### PR TITLE
Fix issue with memory leak and improve rendering performance

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jakutis** [comment]
This is probably the solution, but how exactly do you see the example script proving that the solution is correct? Can you do a screen recording and tell where to look?

**Comment by ghost** [comment]
It can be seen while profiling heap changes over time e.g. `node --heap-prof examples/memory-leak.js` and analyze it in Developer Tools e.g. in Chrome or any other compatible tool.

**Comment by ghost** [comment]
The easiest way is just monitor the process with `htop` or any other process management tool

**Comment by ghost** [comment]
With regard to perf, you can even see the boost when running tests. Before, each test case takes ~500 ms to complete and now it takes ~200 ms

**Comment by jakutis** [comment]
Thank you, now I added these metrics to the test script and arguably made the performance fix more understandable. Will release this now into v1.3.2

**Review by jakutis — APPROVED** [review]

**Comment by ghost** [comment]
Thanks! This memory leak was haunting node-platform and serverless for months and now, few days ago, it is finally started getting OOM in tests, blocking us from going further. I'll propagate the updated package up to the chain.

**Pull request merged**
