### PR TITLE
Upgrade Opal to 1.0.3

### PR DESCRIPTION
**Pull request by ghost**
We've started getting OOM in one of our services (when running tests) and initial profiling showed that 45% of total CPU time spent in rendering the ERB files. The same applies to memory consumption, this module is heavy.

So I'm wondering if we could upgrade the outdated Opal (which uses a five-year-old version) and get all the delicate stuff. At least, I hope.

If not, we will continue investigating the issue but it is always good to have updated stuff, right 😺

### CODE REVIEW

**Comment by jakutis** [comment]
Hey, a dependencies upgrade is well overdue :) Let's do this now!

**Comment by ghost** [comment]
I've fixed several breaking changes already, but still getting the most annoying

```
LoadError: cannot load such file -- erb
```

Asked in their Gitter (https://gitter.im/opal/opal?at=5f807a28a605930a789b6ca5), will be waiting for some feedback, because I'm out of ideas.

**Comment by ghost** [comment]
Opened an issue - https://github.com/opal/opal/issues/2126, Gitter seems like abandoned

**Comment by hmdne** [comment]
@ghaiklor-wix We are mostly talking on Slack now.

Regarding this, I would suggest a totally different approach. It's no secret that opal-parser is heavy (especially when used in JS). But there's some little known feature of Opal that allows you to compile .erb (actually .opalerb) directly to JS using Ruby-evaluated opal-parser. Therefore, your server won't require opal-parser at all.

https://opalrb.com/docs/guides/master/templates.html

**Comment by ghost** [comment]
Hi @hmdne 

Thanks for a hint, looking through it. Although, I'm not sure how can we integrate it, so from the user perspective it will be like calling a JavaScript function.

Latest stable release of this module provides an API:

```
erb({
  timeout: 5000,
  data: data,
  template: '<%= @first %> had <%= title(1) %> <%= additions %>.\n<%= @second %> had <%= title(2, 3) %> <%= additions %>.'
}).then(console.log, console.error);
```

So you can provide a string (erb template) from JavaScript and get the rendered string. I'll be digging templates support in Opal as for now 🤔

**Comment by hmdne** [comment]
Looking shortly at your code, it seems like you already use the template system of opal but:

https://github.com/wix/erb/blob/master/lib/erb/templates/runOpal.js#L5

This looks to me as if you compiled the template each time you rendered it. That's certainly a waste.

**Comment by ghost** [comment]
Thanks to @hmdne help, I was able to run smoke tests again 1.0.3 and overall everything is passed except some cornercases. So it is higly possible to be a breaking update and major release.

For now, I'm investing time into optimization

**Comment by jakutis** [comment]
This is great, will do several distinct commits, with you as a co-author

**Comment by jakutis** [comment]
Okey, currently upgraded Opal is now in master, and the build is now green. Now will follow your optimizations and infra improvements.

**Comment by ghost** [comment]
@jakutis hm, how does it green if I'm seeing failing tests locally 🤔

**Comment by jakutis** [comment]
probably need to do fresh clone

**Comment by ghost** [comment]
@jakutis I thought you will commit in this branch 😢 Now we have conflicts

**Comment by jakutis** [comment]
I will not do one big commit. Also we agreed to perform only dependency upgrade

**Comment by jakutis** [comment]
What is the exact list of breaking changes for the user? To justify major version bump

**Comment by ghost** [comment]
I'm seeing failing tests, that is why breaking change as for now.

**Comment by jakutis** [comment]
Don't waste too much effort on this. From this PR I will use very little, and in separate commits. Now looking only for the performance improvement - there was an idea to not recompile same templates more than once?

**Comment by ghost** [comment]
Yes, make a cache with compiled Ruby -> JS code and if the cache already have it, do not compile through ERB.$compile

**Comment by ghost** [comment]
Let's do this in separate PR, I'll rollback here anything related to the code and leave just dot files and regulard npm updates. I'll start again in new PR

**Comment by jakutis** [comment]
Also skip the dotfiles changes, or comment here why they must be done

**Comment by ghost** [comment]
Some of them are deprecated, others just to give it a fresh look. If you don't want to merge them, let us close the PR

**Comment by ghost** [comment]
I'll update dependencies in another PR, optimization also in another

**Comment by jakutis** [comment]
Great :)

**Pull request closed without merging**
